### ISSUE TITLE
No response when clicking `Login with NEAR` button on Paras

### ISSUE THREAD

**Issue by think-in-universe** [ParasHQ/paras-landing#155]
### Description

Open https://paras.id/ and click Login button. In the new page, click "Login with NEAR", but the page is not redirected to NEAR wallet after click. 

<img width="567" alt="WechatIMG777" src="https://user-images.githubusercontent.com/46699230/138559092-96894a21-aa2f-4246-b181-b33c0da54050.png">

**Comment by emarai** [comment]
Closing old ticket, should be fixed by now
