### ISSUE TITLE
Analytic Improvement - Frontend

### ISSUE THREAD

**Issue by ahnafalfariza** [ParasHQ/paras-landing#713]
Todo

1. add event/check event untuk "Konversi pembelian dari sebuah page" untuk di develop dan di sync ke google analytic
2. Bikin analytic endpoint di frontend untuk ngecek active users
3. Add event untuk user ketika nge-"Flip" kartu (klik sekali di kartu).

**Comment by ekkirinaldi** [comment]
4. Likes double click OR tap
