### ISSUE TITLE
Integrate Ramper SDK

### ISSUE THREAD

**Issue by ahnafalfariza** [ParasHQ/paras-landing#893]
https://docs.ramper.xyz/

**Comment by ekkirinaldi** [comment]
![Image](https://user-images.githubusercontent.com/22832454/187090170-0d01cd72-a52d-4dbf-a81d-b58f4431bda2.png)

Ada wording yang perlu dibenerin



![Image](https://user-images.githubusercontent.com/22832454/187090184-3c1bb2ff-024d-4ca3-8dc0-a52260981a49.png)

@ahnafalfariza misal bagian email disini dihapus bisa gak ya?

**Comment by ahnafalfariza** [comment]
bisa bisa om
