### ISSUE TITLE
Card Detail Iteration 2 (pending design mobile)

### ISSUE THREAD

**Issue by EdoWahdana** [ParasHQ/paras-landing#947]
Figma Link:
https://www.figma.com/file/QEa76OHf1zFBR2t2Vbi3SY/Card-Details---Iteration-2?node-id=4%3A45

Find the pages (Left Area in Figma Window) > ~~~ Handoff ~~~> ✅ [Eng] 09/05 Final Designs

**Comment by emarai** [comment]
Pending: integration with API

**Comment by EdoWahdana** [comment]
https://pr-959---paras-landing-bjmgxdtb2q-as.a.run.app/
